behaviors:
  WalkerStatic_flat:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.01
        encoding_size: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 1000
    summary_freq: 30000
    threaded: true
